//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace AindBehaviorDirectedForagingDataSchema
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class AindBehaviorDirectedForagingRig
    {
    
        private string _aindBehaviorServicesPkgVersion;
    
        private string _version;
    
        private string _computerName;
    
        private string _rigName;
    
        private string _dataDirectory;
    
        private HarpDelphiController _harpDelphiController;
    
        public AindBehaviorDirectedForagingRig()
        {
            _aindBehaviorServicesPkgVersion = "0.13.2";
            _version = "0.0.0-rc0";
            _harpDelphiController = new HarpDelphiController();
        }
    
        protected AindBehaviorDirectedForagingRig(AindBehaviorDirectedForagingRig other)
        {
            _aindBehaviorServicesPkgVersion = other._aindBehaviorServicesPkgVersion;
            _version = other._version;
            _computerName = other._computerName;
            _rigName = other._rigName;
            _dataDirectory = other._dataDirectory;
            _harpDelphiController = other._harpDelphiController;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("aind_behavior_services_pkg_version")]
        public string AindBehaviorServicesPkgVersion
        {
            get
            {
                return _aindBehaviorServicesPkgVersion;
            }
            set
            {
                _aindBehaviorServicesPkgVersion = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
    
        /// <summary>
        /// Computer name
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("computer_name", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Computer name")]
        public string ComputerName
        {
            get
            {
                return _computerName;
            }
            set
            {
                _computerName = value;
            }
        }
    
        /// <summary>
        /// Rig name
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("rig_name", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Rig name")]
        public string RigName
        {
            get
            {
                return _rigName;
            }
            set
            {
                _rigName = value;
            }
        }
    
        /// <summary>
        /// Directory where data will be saved to
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("data_directory", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Directory where data will be saved to")]
        public string DataDirectory
        {
            get
            {
                return _dataDirectory;
            }
            set
            {
                _dataDirectory = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("harp_delphi_controller", Required=Newtonsoft.Json.Required.Always)]
        public HarpDelphiController HarpDelphiController
        {
            get
            {
                return _harpDelphiController;
            }
            set
            {
                _harpDelphiController = value;
            }
        }
    
        public System.IObservable<AindBehaviorDirectedForagingRig> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new AindBehaviorDirectedForagingRig(this)));
        }
    
        public System.IObservable<AindBehaviorDirectedForagingRig> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new AindBehaviorDirectedForagingRig(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("AindBehaviorServicesPkgVersion = " + _aindBehaviorServicesPkgVersion + ", ");
            stringBuilder.Append("Version = " + _version + ", ");
            stringBuilder.Append("ComputerName = " + _computerName + ", ");
            stringBuilder.Append("RigName = " + _rigName + ", ");
            stringBuilder.Append("DataDirectory = " + _dataDirectory + ", ");
            stringBuilder.Append("HarpDelphiController = " + _harpDelphiController);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Main task logic model for the directed-foraging task.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Main task logic model for the directed-foraging task.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class AindBehaviorDirectedForagingTaskLogic
    {
    
        private string _name;
    
        private string _description;
    
        private AindBehaviorDirectedForagingTaskParameters _taskParameters;
    
        private string _version;
    
        private string _stageName;
    
        public AindBehaviorDirectedForagingTaskLogic()
        {
            _name = "AindBehaviorDirectedForaging";
            _description = "";
            _taskParameters = new AindBehaviorDirectedForagingTaskParameters();
            _version = "0.0.0-rc0";
        }
    
        protected AindBehaviorDirectedForagingTaskLogic(AindBehaviorDirectedForagingTaskLogic other)
        {
            _name = other._name;
            _description = other._description;
            _taskParameters = other._taskParameters;
            _version = other._version;
            _stageName = other._stageName;
        }
    
        /// <summary>
        /// Name of the task logic
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("name")]
        [System.ComponentModel.DescriptionAttribute("Name of the task logic")]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
    
        /// <summary>
        /// Description of the task.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("description")]
        [System.ComponentModel.DescriptionAttribute("Description of the task.")]
        public string Description
        {
            get
            {
                return _description;
            }
            set
            {
                _description = value;
            }
        }
    
        /// <summary>
        /// Parameters of the task logic
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("task_parameters", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Parameters of the task logic")]
        public AindBehaviorDirectedForagingTaskParameters TaskParameters
        {
            get
            {
                return _taskParameters;
            }
            set
            {
                _taskParameters = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
    
        /// <summary>
        /// Optional stage name the `Task` object instance represents.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("stage_name")]
        [System.ComponentModel.DescriptionAttribute("Optional stage name the `Task` object instance represents.")]
        public string StageName
        {
            get
            {
                return _stageName;
            }
            set
            {
                _stageName = value;
            }
        }
    
        public System.IObservable<AindBehaviorDirectedForagingTaskLogic> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new AindBehaviorDirectedForagingTaskLogic(this)));
        }
    
        public System.IObservable<AindBehaviorDirectedForagingTaskLogic> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new AindBehaviorDirectedForagingTaskLogic(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Name = " + _name + ", ");
            stringBuilder.Append("Description = " + _description + ", ");
            stringBuilder.Append("TaskParameters = " + _taskParameters + ", ");
            stringBuilder.Append("Version = " + _version + ", ");
            stringBuilder.Append("StageName = " + _stageName);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Complete parameter specification for the directed-foraging task.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Complete parameter specification for the directed-foraging task.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class AindBehaviorDirectedForagingTaskParameters
    {
    
        private double? _rngSeed;
    
        private string _aindBehaviorServicesPkgVersion;
    
        private System.Collections.Generic.List<Trial> _trials;
    
        public AindBehaviorDirectedForagingTaskParameters()
        {
            _aindBehaviorServicesPkgVersion = "0.13.2";
            _trials = new System.Collections.Generic.List<Trial>();
        }
    
        protected AindBehaviorDirectedForagingTaskParameters(AindBehaviorDirectedForagingTaskParameters other)
        {
            _rngSeed = other._rngSeed;
            _aindBehaviorServicesPkgVersion = other._aindBehaviorServicesPkgVersion;
            _trials = other._trials;
        }
    
        /// <summary>
        /// Seed of the random number generator
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("rng_seed")]
        [System.ComponentModel.DescriptionAttribute("Seed of the random number generator")]
        public double? RngSeed
        {
            get
            {
                return _rngSeed;
            }
            set
            {
                _rngSeed = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("aind_behavior_services_pkg_version")]
        public string AindBehaviorServicesPkgVersion
        {
            get
            {
                return _aindBehaviorServicesPkgVersion;
            }
            set
            {
                _aindBehaviorServicesPkgVersion = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("trials", Required=Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.List<Trial> Trials
        {
            get
            {
                return _trials;
            }
            set
            {
                _trials = value;
            }
        }
    
        public System.IObservable<AindBehaviorDirectedForagingTaskParameters> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new AindBehaviorDirectedForagingTaskParameters(this)));
        }
    
        public System.IObservable<AindBehaviorDirectedForagingTaskParameters> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new AindBehaviorDirectedForagingTaskParameters(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("RngSeed = " + _rngSeed + ", ");
            stringBuilder.Append("AindBehaviorServicesPkgVersion = " + _aindBehaviorServicesPkgVersion + ", ");
            stringBuilder.Append("Trials = " + _trials);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class BaseModel
    {
    
        public BaseModel()
        {
        }
    
        protected BaseModel(BaseModel other)
        {
        }
    
        public System.IObservable<BaseModel> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new BaseModel(this)));
        }
    
        public System.IObservable<BaseModel> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new BaseModel(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            return false;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class HarpDelphiController
    {
    
        private string _deviceType;
    
        private BaseModel _calibration;
    
        private int _whoAmI;
    
        private string _serialNumber;
    
        private string _portName;
    
        private bool _enableValveLeds;
    
        private double _minimumPokeTime;
    
        private double _minimumOdorDeliveryTime;
    
        private double _finalValveEnergizedTime;
    
        private double _vacuumSetupTime;
    
        private double _vacuumCloseTime;
    
        private double _odorTransitionTime;
    
        private double _maxOdorDeliveryTime;
    
        public HarpDelphiController()
        {
            _deviceType = "DelphiController";
            _whoAmI = 1409;
            _minimumPokeTime = 0.1D;
            _minimumOdorDeliveryTime = 0.5D;
            _finalValveEnergizedTime = 0.11D;
            _vacuumSetupTime = 0.01D;
            _vacuumCloseTime = 0.02D;
            _odorTransitionTime = 0.02D;
            _maxOdorDeliveryTime = 0.6D;
        }
    
        protected HarpDelphiController(HarpDelphiController other)
        {
            _deviceType = other._deviceType;
            _calibration = other._calibration;
            _whoAmI = other._whoAmI;
            _serialNumber = other._serialNumber;
            _portName = other._portName;
            _enableValveLeds = other._enableValveLeds;
            _minimumPokeTime = other._minimumPokeTime;
            _minimumOdorDeliveryTime = other._minimumOdorDeliveryTime;
            _finalValveEnergizedTime = other._finalValveEnergizedTime;
            _vacuumSetupTime = other._vacuumSetupTime;
            _vacuumCloseTime = other._vacuumCloseTime;
            _odorTransitionTime = other._odorTransitionTime;
            _maxOdorDeliveryTime = other._maxOdorDeliveryTime;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("device_type")]
        public string DeviceType
        {
            get
            {
                return _deviceType;
            }
            set
            {
                _deviceType = value;
            }
        }
    
        /// <summary>
        /// Calibration for the device.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("calibration")]
        [System.ComponentModel.DescriptionAttribute("Calibration for the device.")]
        public BaseModel Calibration
        {
            get
            {
                return _calibration;
            }
            set
            {
                _calibration = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("who_am_i")]
        public int WhoAmI
        {
            get
            {
                return _whoAmI;
            }
            set
            {
                _whoAmI = value;
            }
        }
    
        /// <summary>
        /// Device serial number
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("serial_number")]
        [System.ComponentModel.DescriptionAttribute("Device serial number")]
        public string SerialNumber
        {
            get
            {
                return _serialNumber;
            }
            set
            {
                _serialNumber = value;
            }
        }
    
        /// <summary>
        /// Device port name
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("port_name", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Device port name")]
        public string PortName
        {
            get
            {
                return _portName;
            }
            set
            {
                _portName = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("enable_valve_leds", Required=Newtonsoft.Json.Required.Always)]
        public bool EnableValveLeds
        {
            get
            {
                return _enableValveLeds;
            }
            set
            {
                _enableValveLeds = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("minimum_poke_time")]
        public double MinimumPokeTime
        {
            get
            {
                return _minimumPokeTime;
            }
            set
            {
                _minimumPokeTime = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("minimum_odor_delivery_time")]
        public double MinimumOdorDeliveryTime
        {
            get
            {
                return _minimumOdorDeliveryTime;
            }
            set
            {
                _minimumOdorDeliveryTime = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("final_valve_energized_time")]
        public double FinalValveEnergizedTime
        {
            get
            {
                return _finalValveEnergizedTime;
            }
            set
            {
                _finalValveEnergizedTime = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("vacuum_setup_time")]
        public double VacuumSetupTime
        {
            get
            {
                return _vacuumSetupTime;
            }
            set
            {
                _vacuumSetupTime = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("vacuum_close_time")]
        public double VacuumCloseTime
        {
            get
            {
                return _vacuumCloseTime;
            }
            set
            {
                _vacuumCloseTime = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("odor_transition_time")]
        public double OdorTransitionTime
        {
            get
            {
                return _odorTransitionTime;
            }
            set
            {
                _odorTransitionTime = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("max_odor_delivery_time")]
        public double MaxOdorDeliveryTime
        {
            get
            {
                return _maxOdorDeliveryTime;
            }
            set
            {
                _maxOdorDeliveryTime = value;
            }
        }
    
        public System.IObservable<HarpDelphiController> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new HarpDelphiController(this)));
        }
    
        public System.IObservable<HarpDelphiController> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new HarpDelphiController(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("DeviceType = " + _deviceType + ", ");
            stringBuilder.Append("Calibration = " + _calibration + ", ");
            stringBuilder.Append("WhoAmI = " + _whoAmI + ", ");
            stringBuilder.Append("SerialNumber = " + _serialNumber + ", ");
            stringBuilder.Append("PortName = " + _portName + ", ");
            stringBuilder.Append("EnableValveLeds = " + _enableValveLeds + ", ");
            stringBuilder.Append("MinimumPokeTime = " + _minimumPokeTime + ", ");
            stringBuilder.Append("MinimumOdorDeliveryTime = " + _minimumOdorDeliveryTime + ", ");
            stringBuilder.Append("FinalValveEnergizedTime = " + _finalValveEnergizedTime + ", ");
            stringBuilder.Append("VacuumSetupTime = " + _vacuumSetupTime + ", ");
            stringBuilder.Append("VacuumCloseTime = " + _vacuumCloseTime + ", ");
            stringBuilder.Append("OdorTransitionTime = " + _odorTransitionTime + ", ");
            stringBuilder.Append("MaxOdorDeliveryTime = " + _maxOdorDeliveryTime);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class OdorDefinition
    {
    
        private string _odorId;
    
        private int _olfactometerMask;
    
        public OdorDefinition()
        {
        }
    
        protected OdorDefinition(OdorDefinition other)
        {
            _odorId = other._odorId;
            _olfactometerMask = other._olfactometerMask;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("odor_id", Required=Newtonsoft.Json.Required.Always)]
        public string OdorId
        {
            get
            {
                return _odorId;
            }
            set
            {
                _odorId = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("olfactometer_mask", Required=Newtonsoft.Json.Required.Always)]
        public int OlfactometerMask
        {
            get
            {
                return _olfactometerMask;
            }
            set
            {
                _olfactometerMask = value;
            }
        }
    
        public System.IObservable<OdorDefinition> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new OdorDefinition(this)));
        }
    
        public System.IObservable<OdorDefinition> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new OdorDefinition(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("OdorId = " + _odorId + ", ");
            stringBuilder.Append("OlfactometerMask = " + _olfactometerMask);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Session
    {
    
        private string _aindBehaviorServicesPkgVersion;
    
        private string _version;
    
        private string _experiment;
    
        private System.Collections.Generic.List<string> _experimenter;
    
        private System.DateTimeOffset _date;
    
        private string _sessionName;
    
        private string _subject;
    
        private string _notes;
    
        private string _commitHash;
    
        private bool _allowDirtyRepo;
    
        private bool _skipHardwareValidation;
    
        public Session()
        {
            _aindBehaviorServicesPkgVersion = "0.13.2";
            _version = "0.13.2";
            _experimenter = new System.Collections.Generic.List<string>();
            _allowDirtyRepo = false;
            _skipHardwareValidation = false;
        }
    
        protected Session(Session other)
        {
            _aindBehaviorServicesPkgVersion = other._aindBehaviorServicesPkgVersion;
            _version = other._version;
            _experiment = other._experiment;
            _experimenter = other._experimenter;
            _date = other._date;
            _sessionName = other._sessionName;
            _subject = other._subject;
            _notes = other._notes;
            _commitHash = other._commitHash;
            _allowDirtyRepo = other._allowDirtyRepo;
            _skipHardwareValidation = other._skipHardwareValidation;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("aind_behavior_services_pkg_version")]
        public string AindBehaviorServicesPkgVersion
        {
            get
            {
                return _aindBehaviorServicesPkgVersion;
            }
            set
            {
                _aindBehaviorServicesPkgVersion = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
    
        /// <summary>
        /// Name of the experiment
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("experiment")]
        [System.ComponentModel.DescriptionAttribute("Name of the experiment")]
        public string Experiment
        {
            get
            {
                return _experiment;
            }
            set
            {
                _experiment = value;
            }
        }
    
        /// <summary>
        /// Name of the experimenter
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("experimenter")]
        [System.ComponentModel.DescriptionAttribute("Name of the experimenter")]
        public System.Collections.Generic.List<string> Experimenter
        {
            get
            {
                return _experimenter;
            }
            set
            {
                _experimenter = value;
            }
        }
    
        /// <summary>
        /// Date of the experiment
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("date")]
        [System.ComponentModel.DescriptionAttribute("Date of the experiment")]
        public System.DateTimeOffset Date
        {
            get
            {
                return _date;
            }
            set
            {
                _date = value;
            }
        }
    
        /// <summary>
        /// Name of the session. This will be used to create a folder in the root path. If not provided, it will be generated using subject and date.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("session_name")]
        [System.ComponentModel.DescriptionAttribute("Name of the session. This will be used to create a folder in the root path. If no" +
            "t provided, it will be generated using subject and date.")]
        public string SessionName
        {
            get
            {
                return _sessionName;
            }
            set
            {
                _sessionName = value;
            }
        }
    
        /// <summary>
        /// Name of the subject
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("subject", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Name of the subject")]
        public string Subject
        {
            get
            {
                return _subject;
            }
            set
            {
                _subject = value;
            }
        }
    
        /// <summary>
        /// Notes about the experiment
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("notes")]
        [System.ComponentModel.DescriptionAttribute("Notes about the experiment")]
        public string Notes
        {
            get
            {
                return _notes;
            }
            set
            {
                _notes = value;
            }
        }
    
        /// <summary>
        /// Commit hash of the repository
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("commit_hash")]
        [System.ComponentModel.DescriptionAttribute("Commit hash of the repository")]
        public string CommitHash
        {
            get
            {
                return _commitHash;
            }
            set
            {
                _commitHash = value;
            }
        }
    
        /// <summary>
        /// Allow running from a dirty repository
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("allow_dirty_repo")]
        [System.ComponentModel.DescriptionAttribute("Allow running from a dirty repository")]
        public bool AllowDirtyRepo
        {
            get
            {
                return _allowDirtyRepo;
            }
            set
            {
                _allowDirtyRepo = value;
            }
        }
    
        /// <summary>
        /// Skip hardware validation
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("skip_hardware_validation")]
        [System.ComponentModel.DescriptionAttribute("Skip hardware validation")]
        public bool SkipHardwareValidation
        {
            get
            {
                return _skipHardwareValidation;
            }
            set
            {
                _skipHardwareValidation = value;
            }
        }
    
        public System.IObservable<Session> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Session(this)));
        }
    
        public System.IObservable<Session> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Session(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("AindBehaviorServicesPkgVersion = " + _aindBehaviorServicesPkgVersion + ", ");
            stringBuilder.Append("Version = " + _version + ", ");
            stringBuilder.Append("Experiment = " + _experiment + ", ");
            stringBuilder.Append("Experimenter = " + _experimenter + ", ");
            stringBuilder.Append("Date = " + _date + ", ");
            stringBuilder.Append("SessionName = " + _sessionName + ", ");
            stringBuilder.Append("Subject = " + _subject + ", ");
            stringBuilder.Append("Notes = " + _notes + ", ");
            stringBuilder.Append("CommitHash = " + _commitHash + ", ");
            stringBuilder.Append("AllowDirtyRepo = " + _allowDirtyRepo + ", ");
            stringBuilder.Append("SkipHardwareValidation = " + _skipHardwareValidation);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Trial
    {
    
        private OdorDefinition _odorDefinition;
    
        private double _releaseTime;
    
        private double _digThreshold;
    
        private double _trialTimeout;
    
        private int _thresholdReward;
    
        private double _thresholdPunishment;
    
        public Trial()
        {
            _odorDefinition = new OdorDefinition();
        }
    
        protected Trial(Trial other)
        {
            _odorDefinition = other._odorDefinition;
            _releaseTime = other._releaseTime;
            _digThreshold = other._digThreshold;
            _trialTimeout = other._trialTimeout;
            _thresholdReward = other._thresholdReward;
            _thresholdPunishment = other._thresholdPunishment;
        }
    
        /// <summary>
        /// The odor that will be released on this trial
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("odor_definition", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The odor that will be released on this trial")]
        public OdorDefinition OdorDefinition
        {
            get
            {
                return _odorDefinition;
            }
            set
            {
                _odorDefinition = value;
            }
        }
    
        /// <summary>
        /// The amount of time this odor will be released
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("release_time", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The amount of time this odor will be released")]
        public double ReleaseTime
        {
            get
            {
                return _releaseTime;
            }
            set
            {
                _releaseTime = value;
            }
        }
    
        /// <summary>
        /// The distance a subject must dig before reward delivery, if reward is available
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("dig_threshold", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The distance a subject must dig before reward delivery, if reward is available")]
        public double DigThreshold
        {
            get
            {
                return _digThreshold;
            }
            set
            {
                _digThreshold = value;
            }
        }
    
        /// <summary>
        /// Subject must begin digging within this amount of time to register a response
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("trial_timeout", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Subject must begin digging within this amount of time to register a response")]
        public double TrialTimeout
        {
            get
            {
                return _trialTimeout;
            }
            set
            {
                _trialTimeout = value;
            }
        }
    
        /// <summary>
        /// Reward amount to be delivered when threshold reached
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("threshold_reward", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Reward amount to be delivered when threshold reached")]
        public int ThresholdReward
        {
            get
            {
                return _thresholdReward;
            }
            set
            {
                _thresholdReward = value;
            }
        }
    
        /// <summary>
        /// Punishment time added when threshold is reached
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("threshold_punishment", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Punishment time added when threshold is reached")]
        public double ThresholdPunishment
        {
            get
            {
                return _thresholdPunishment;
            }
            set
            {
                _thresholdPunishment = value;
            }
        }
    
        public System.IObservable<Trial> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Trial(this)));
        }
    
        public System.IObservable<Trial> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Trial(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("OdorDefinition = " + _odorDefinition + ", ");
            stringBuilder.Append("ReleaseTime = " + _releaseTime + ", ");
            stringBuilder.Append("DigThreshold = " + _digThreshold + ", ");
            stringBuilder.Append("TrialTimeout = " + _trialTimeout + ", ");
            stringBuilder.Append("ThresholdReward = " + _thresholdReward + ", ");
            stringBuilder.Append("ThresholdPunishment = " + _thresholdPunishment);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToJson
    {
    
        public Newtonsoft.Json.Formatting Formatting { get; set; }

        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            var formatting = Formatting;
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value, formatting));
        }

        public System.IObservable<string> Process(System.IObservable<AindBehaviorDirectedForagingRig> source)
        {
            return Process<AindBehaviorDirectedForagingRig>(source);
        }

        public System.IObservable<string> Process(System.IObservable<AindBehaviorDirectedForagingTaskLogic> source)
        {
            return Process<AindBehaviorDirectedForagingTaskLogic>(source);
        }

        public System.IObservable<string> Process(System.IObservable<AindBehaviorDirectedForagingTaskParameters> source)
        {
            return Process<AindBehaviorDirectedForagingTaskParameters>(source);
        }

        public System.IObservable<string> Process(System.IObservable<BaseModel> source)
        {
            return Process<BaseModel>(source);
        }

        public System.IObservable<string> Process(System.IObservable<HarpDelphiController> source)
        {
            return Process<HarpDelphiController>(source);
        }

        public System.IObservable<string> Process(System.IObservable<OdorDefinition> source)
        {
            return Process<OdorDefinition>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Session> source)
        {
            return Process<Session>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Trial> source)
        {
            return Process<Trial>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<AindBehaviorDirectedForagingRig>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<AindBehaviorDirectedForagingTaskLogic>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<AindBehaviorDirectedForagingTaskParameters>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<BaseModel>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<HarpDelphiController>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<OdorDefinition>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Session>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Trial>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<AindBehaviorDirectedForagingRig>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }
}